### PR TITLE
[fix]fixed Emoji filename

### PR DESCRIPTION
**Pull request by siiramone**
Because there is a possibility that the file name may be duplicated, I fixed it so that it saves with the Emoji name.

### CODE REVIEW

**Comment by from-unknown** [comment]
Thanks for PR and I understand idea.
Looks good to me.
Before merge your PR, I have one question that I believe these two codes give the same result, so is there any reason to choose 1.?

1. `name = (File.dirname(node[1])).match(/^.*\/(.+)$/)[1]+File.extname(node[1])`
2. `name = node[0]+File.extname(node[1])`

I think 2. is a little less processing time, but this overhead is small enough to ignore, so both codes are OK to me.
I would like to merge your PR after hearing your response.

**Comment by siiramone** [comment]
Thank you for reply. I understood what you want to say.
Because I like '2' of your suggests, I will make new commit soon. 
Please just a moment.

**Comment by from-unknown** [comment]
Thank you, I'll check your new PR later today.
I'm just curious to know that file name duplicated problem happened to you or not.

**Comment by siiramone** [comment]
I have finished. Please check it out.

The duplicate problem happened to me.
For example, The following contents are part of 'emoji.txt' in my team's.
>        "yosasou": "https:\/\/emoji.slack-edge.com\/XXX/yosasou\/f0998bacc554705f.png",
>        "zawa": "https:\/\/emoji.slack-edge.com\/XXX/zawa\/f0998bacc554705f.png",

**Comment by from-unknown** [comment]
Looks good and worked fine.
I was thinking this problem rarely happens, but it actually occurred.
Thank you for fixing problem.

**Pull request merged**
